version: '2.1'

services:
  igolftnt-mp:
    image: igolftnt-mp
    build: .
    environment:
      NODE_ENV: development
      MYSQL_URL: '192.168.3.31'
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./bin/www
    network_mode: host
